### ISSUE TITLE
Create Rust Belt album art logo

### ISSUE THREAD

**Issue by johnthagen** [johnthagen/rust-belt#108]
It would be nice to re-brand the rust belt MP3s with a consistent logo with the Github page.

The image should be 1x1 aspect ratio with some discussion here: https://www.blisshq.com/music-library-management-blog/2011/12/05/whats-the-best-album-art-size/

**Comment by mcdenhoed** [comment]
@johnthagen 
![rust-belt-album](https://cloud.githubusercontent.com/assets/325687/24386401/64dc8636-133d-11e7-86b1-f04c30297426.png)

**Comment by johnthagen** [comment]
I'll close this issue once I've update the mp3s and pushed.

**Comment by johnthagen** [comment]
Added in c14ac6b99e1c63897db99f2dc77d3ed9281d0731.
