### ISSUE TITLE
Enable creation of asteroids upon destruction

### ISSUE THREAD

**Issue by mcdenhoed** [johnthagen/rust-belt#126]
Need to add a new asteroid constructor enabling us to specify position and velocity. Call it from the closure dealing with bullet collisions.

**Comment by mcdenhoed** [comment]
Also should enable specifying rotation and rotation speed too...

**Comment by mcdenhoed** [comment]
@johnthagen Would you be opposed to me adding some more methods in Positioned? It would be convenient to add a similar interface onto it for accessing velocities.

**Comment by johnthagen** [comment]
@mcdenhoed  Sure! Yeah whatever you think is needed to get the job done best.

**Comment by mcdenhoed** [comment]
See the [split](https://github.com/johnthagen/rust-belt/tree/split) branch.

**Comment by mcdenhoed** [comment]
Implemented in #130
