### ISSUE TITLE
Add GIF of game being played to README

### ISSUE THREAD

**Issue by johnthagen** [johnthagen/rust-belt#137]
Would be cool to have a GIF showing gameplay on the the README.

**Comment by johnthagen** [comment]
@mcdenhoed Have you ever recorded a GIF from a screen capture before? I think this is the last thing I'd like to get in before 1.2 release 🍾

**Comment by mcdenhoed** [comment]
I have not. Is there anyway to directly export a video from piston? Could make a gif of that then

**Comment by johnthagen** [comment]
Closed in #155
