### ISSUE TITLE
How should we encapsulate how entities are drawn?

### ISSUE THREAD

**Issue by johnthagen** [johnthagen/rust-belt#36]
Currently information about how the player's ship is drawn is located in the `game` module (For example the `SHIP` `triangle`).

Pretty soon (#5, #7, etc) we will be having a lot more entities on the screen. How should the way those entities are drawn be encapsulated? 

`rocket` has a `draw` method on all of its drawable models. I think this is a pretty good strategy. For example, when #28 is implemented, there will be multiple different things being drawn to the screen for the player (boosters in different directions) depending on the state of the `Player`.

I propose a `Drawable` trait that `Player`, `Bullet`, `Asteroid`, (even `Game`?) could implement that exposes a `draw` method.

```rust
/// Draws the entity to the screen.
fn draw(&self, c: &Context, gl: &mut GlGraphics);
```

If it works out well, we could even contribute something like it back to `rocket`.

@mcdenhoed, @theandrewdavis, any thoughts?

**Comment by mcdenhoed** [comment]
I think that sounds reasonable.
