### ISSUE TITLE
Make Vect include velocity?

### ISSUE THREAD

**Issue by johnthagen** [johnthagen/rust-belt#37]
In the `player` module, we have `Vect` which is an x, y coordinate.  I think we'll quickly want to enhance this to also include velocity so it can be shared by `Bullet`'s, `Asteroids`, etc.

`rocket` does:

```rust
/// A `Point` represents a position in space
#[derive(Clone, Default)]
pub struct Point {
    pub x: f64,
    pub y: f64
}

...

/// A `Vector`
#[derive(Clone, Default)]
pub struct Vector {
    /// The position of the vector
    pub position: Point,
    /// The direction angle, in radians
    pub direction: f64
}
```

To me this seems pretty optimal. @mcdenhoed, what do you think?

**Comment by mcdenhoed** [comment]
I think bundling those makes sense. If you look at https://github.com/johnthagen/rust-belt/commit/e4603de630458c170c4ed2478167215b44d29c90, I currently have the enemies actions determined by Player position. If we just had one "position/velocity state struct" get passed around, it could be a natural way to allow for the use of velocity in enemy decisions too.

However, I'm confused by the code example you posted. That struct doesn't seem to me to have enough information to store both position and velocity. Position is obvious, but if you were going to store velocity you need either another set of coordinates or both a direction AND a magnitude. Are you sure they aren't using this to store redundant representations of the position vector?

**Comment by johnthagen** [comment]
Good point. I had forgotten that `rocket` doesn't actually use acceleration, it only provides two speeds (normal and fast) so it doesn't actually need to store the velocity of the player, only it's position and direction.

See: https://github.com/aochagavia/rocket/blob/master/src/game.rs#L197

If we do bundle this together, I asked around to try to determine a good name. Best I could come up with is `MotionState`.

I think at this point we shouldn't bundle and create a new type until it's actually needed (probably not until 2.0 or so) if ever.
