### ISSUE TITLE
How should modules be organized?

### ISSUE THREAD

**Issue by johnthagen** [johnthagen/rust-belt#42]
We'll soon have different types of models (#5 , #14, etc) and the current structure of having all nine modules at the top level is starting to feel a little disorganized. I think it would be worth getting this organized before the weapon is started (#5).

[`rocket`](https://github.com/aochagavia/rocket/tree/master/src) organizes its structure like:

```
main.rs
game.rs
drawing/
    point.rs
    ...
models/
    bullet.rs
    player.rs
    ...
traits/
```

`rust-belt` will be a little different because we have a menu that sits above our game.

A rough sketch:

```
main.rs
menu/
    game/
        models/
            player.rs
            bullet, enemy, etc
            mod.rs (Drawable, Updateable)
        drawing/
            mod.rs (color, Vector, Point, etc?)
        mod.rs (Game)
    mod.rs (Menu)
    story.rs
    settings.rs
```

@mcdenhoed, @theandrewdavis any thoughts on this? I'm unsure if the `menu/` top level directory is necessary, but seemed to model how the game is currently structured.

**Comment by mcdenhoed** [comment]
I'd vote against having menu be the top level, but otherwise, seems reasonable.
