### ISSUE TITLE
Windows Install Instructions Clarification

### ISSUE THREAD

**Issue by mcdenhoed** [johnthagen/rust-belt#44]
The Windows Install instructions say to add the SDL .lib files to the LIB system path. My system (64-bit Windows 10) does not have a LIB environment variable in either the user or the system menu. Do I create this env var if it doesn't exist?

**Comment by johnthagen** [comment]
Yes, we should modify the `README` such that it says something like "Create the `LIB` environment variable if it does not exist, and add..."

This also applies for the MinGW-w64 case and the `LIBRARY_PATH` environment variable.
