### ISSUE TITLE
Refactor common translation update code

### ISSUE THREAD

**Issue by johnthagen** [johnthagen/rust-belt#59]
We have the following code in (soon to be) three places:

```rust
let x = self.pos.x + self.vel.x + self.window_size.width as f64;
let y = self.pos.y + self.vel.y + self.window_size.height as f64;
self.pos.x = x % self.window_size.width as f64;
self.pos.y = y % self.window_size.height as f64;
```

It would be good to refactor this into some kind of trait or function that can be shared between `Updateable` types. Perhaps a sub-trait of `Updateable`, something like `Movable` could expose `pos()` and `vel()`.

Potentially we could simplify this with the new `Vector::add()` as well instead of treating `x` and `y` separately.

**Comment by mcdenhoed** [comment]
@johnthagen  Another thing we should do:
- [ ] Change the physics update logic to use `args.dt`
- [ ] Update the speed scaling constants to be reasonable with `arg.dt` based physics

Might look something like this: 
```rust
let x = self.pos.x + self.vel.x*args.dt + self.window_size.width as f64;
```

**Comment by mcdenhoed** [comment]
Gave that args.dt issue a look. Stress-tested it with a zero'd timeout and a really long ttl. Didn't really see any performance difference compared to how it is now. Still "pauses" when the workload gets especially heavy.

**Comment by johnthagen** [comment]
Sounds good. As long as the normal game runs fine I think it's fine. The "pauses" are probably something we could eventually look at swapping out the backend and/or lowering the resolution of some things, but for now if the game runs fine I don't see it as a big priority.

**Comment by mcdenhoed** [comment]
Agreed. I think we can close this for now.
