### ISSUE TITLE
Reuse common drawing implementation

### ISSUE THREAD

**Issue by johnthagen** [johnthagen/rust-belt#68]
The following code in `Asteroid` looks like it could be the basis for a common drawing default implementation that could be shared by most modules rather than being duplicated:

```rust
    fn draw(&self, context: Context, graphics: &mut GlGraphics) {
        polygon(color::WHITE,
                &self.shape,
                context.transform
                .trans(self.pos.x, self.pos.y)
                .rot_rad(self.rot),
                graphics)
    }
```

Note that the key pieces of information that are needed by the "derived" type would be:

- `color()`
- `shape()`
- `pos()`
- `rot()`

Then the `Drawable` trait (or perhaps a derived trait so that you could just still use `Drawable` without having to necessarily conform to the full specific interface that gives the nice default implementation) would implement something like:

```rust
     fn draw(&self, context: Context, graphics: &mut GlGraphics) {
        polygon(self.color(),
                &self.shape(),
                context.transform
                .trans(self.pos().x, self.pos().y)
                .rot_rad(self.rot()),
                graphics)
    }
```

Relates to #52

**Comment by mcdenhoed** [comment]
We might have to switch from polygon to a list of lines though, (if we're going to a 'hollow' drawing style) right?

**Comment by johnthagen** [comment]
Yes, that's right. We could probably change to a default `polygon()` and then later refactor if we move to hollow objects.

**Comment by mcdenhoed** [comment]
Do we plan on having a background image ever? If so, might want to do black filled objects. Could do two polygons, one white first and then a slightly smaller black copy.

**Comment by johnthagen** [comment]
Yeah, that's not a bad idea. Though, depending on the background, that could also look a little strange since then the drawing wouldn't be transparent. We can play around with it when we get to that point.

**Comment by johnthagen** [comment]
Players draw more than one polygon, bullets are ellipses, so not that many models would benefit from a default implementation.
