### ISSUE TITLE
Refactor Asteroid Start State

### ISSUE THREAD

**Issue by mcdenhoed** [johnthagen/rust-belt#79]
Right now, asteroids are spawned within the window, causing them to appear instantly. 

We should modify them so that they are spawned OUTSIDE the window and then can drift in. Once they have drifted in, we can have their position wrap like it does now.

As a side-effect this should alleviate (to some degree) the issue of an asteroid spawning on a player.

**Comment by mcdenhoed** [comment]
Attempted in https://github.com/johnthagen/rust-belt/tree/asteroid-spawning

**Comment by johnthagen** [comment]
Added comments on #7

**Comment by johnthagen** [comment]
Closed with #84
