### ISSUE TITLE
Collision detection

### ISSUE THREAD

**Issue by johnthagen** [johnthagen/rust-belt#8]
We'll want something generic since we'll need it for at least weapon bullets, asteroids, and the player.

See: https://github.com/aochagavia/rocket/blob/aaeb23a5412ff0c1445ffe286aed93c1a0615f94/src/traits/mod.rs#L76

- [x] Bullets colliding with Asteroids
- [x] Asteroids colliding with Player
- [x] ~~Asteroids colliding with each other~~ In the original, asteroids can't collide with each other, which I think is probably better for game play anyway.

**Comment by johnthagen** [comment]
Work in progress: https://github.com/johnthagen/rust-belt/tree/collision

**Comment by johnthagen** [comment]
@drhagen suggested using [`Iterator.partition`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.partition) to more ergonomically handle collision detection and resolution.

cc @mcdenhoed

**Comment by mcdenhoed** [comment]
@johnthagen hahaha yeah I found partition last night and tried to rewrite using it but kept hitting the borrow checker, so I never finished it.
