### ISSUE TITLE
Game Over Screen

### ISSUE THREAD

**Issue by mcdenhoed** [johnthagen/rust-belt#95]
When the player gets hit by an asteroid, the game immediately goes back to the main menu. It might be nice to instead go to a game-over screen displaying the player's score, and from there go to the menu. Could even display local high scores there.

**Comment by johnthagen** [comment]
👍 After 1.0 is released (should be soon, mostly just need to document everything), I'd like to discuss the roadmap going forward and what people are interested in working on.

**Comment by mcdenhoed** [comment]
@johnthagen Pushed a test implementation of this to https://github.com/johnthagen/rust-belt/tree/gameover.

Main problem with it  that I can see is that the text isn't centered. Any way to get the size of rendered glyphs?

**Comment by mcdenhoed** [comment]
Another problem: If you have a key pressed while getting hit, the loop keeps receiving keypress events and pretty much flashes through the game over screen instantly. Should figure out a good way to make sure that a NEW press/release happens before moving on.

**Comment by johnthagen** [comment]
@mcdenhoed I've manually centered the text before (that is how the menu works). I haven't seen a way to get a fonts size (and it would be character dependent for most fonts too).

I do see the problem if the player is holding a button at the time of death. I wonder if we could do something like checking for an `Input::Press` followed by an `Input::Release`.

I've pushed some changes to the branch.

**Comment by johnthagen** [comment]
@mcdenhoed See what you think of the latest changes in the `gameover` branch.

**Comment by mcdenhoed** [comment]
Looks good! Took out some duplicate code and made the keypress stuff a little more robust. Also ran with updated rustfmt, which seems to be a very quickly moving target.

**Comment by johnthagen** [comment]
Should the game over screen actually say `Game Over` or something other than just the score?

**Comment by johnthagen** [comment]
Closed by #140
