### ISSUE TITLE
Implement Drawable for Game

### ISSUE THREAD

**Issue by johnthagen** [johnthagen/rust-belt#98]
Per https://github.com/johnthagen/rust-belt/pull/97#issuecomment-285918027, it would be a bit more consistent if we used the `Drawable` trait on `Game` rather than having a `draw` method hanging out in the `impl`.

Since `Drawable::draw` doesn't take the `GlypheCache`, we'll need to pass it into the constructor of `Game` so it's available in `self`.

I worked on this a little bit, but hit some lifetime struggles, but it was the first time I had ever tried using lifetimes.

**Comment by johnthagen** [comment]
After [several](https://stackoverflow.com/questions/43023441/how-can-you-resolve-the-need-to-mutably-borrow-in-different-match-arms-in-rust/) [attempts](https://users.rust-lang.org/t/trouble-with-struct-lifetime-that-borrows-a-mutable-reference-to-another-struct/10088), I've come to the conclusion that storing mutable references should be avoided. This stems mostly from what seem to be deficiencies in the resolution of rustc borrow checker.

In this case, we couldn't implement `Drawable` on a type with a `GlyphCache` because it requires a  `&mut self` rather than `&self`. It seemed like a net loss to do it in this particular case.

@mcdenhoed I'm nominating this issue for closing.

**Comment by mcdenhoed** [comment]
Agreed!

**Comment by johnthagen** [comment]
Farewell for now, lifetimes. You may have won today, but we shall meet again in battle someday.
